### ISSUE TITLE
showLevel 2 does not display H2 headers

### ISSUE THREAD

**Issue by Soitora** [xuekai-china/vuepress-plugin-right-anchor#1]
As title suggests, `showLevel: 2` does not display H2 headers while `showLevel: 1` only displays H2 headers. How do I make it display both H2 and H3? This would be perfect for my site.

Thank you :)

**Comment by xuek9900** [comment]
> 如标题所示，`showLevel: 2`不显示H2标头，而`showLevel: 1`仅显示H2标头。如何使其同时显示H2和H3？这对我的网站而言是完美的。
> 
> 谢谢 ：）

First of all, I'm sorry, I haven't paid attention to this plug-in for a long time because of my work.

**Comment by xuek9900** [comment]
> As title suggests, `showLevel: 2` does not display H2 headers while `showLevel: 1` only displays H2 headers. How do I make it display both H2 and H3? This would be perfect for my site.
> 
> Thank you :)

As the document says, the parameter showlevel has the same meaning as sidebardepth in the vuepress document. So 1 points to H2 and 2 to H3. 

As for displaying H2 and H3 at the same time, I neglected this requirement in the design. My initial idea was a simple navigation menu. Thank you for your advice. I will implement it later.
