### ISSUE TITLE
与@vuepress/plugin-back-to-top一起使用时的问题

### ISSUE THREAD

**Issue by kk305cs** [xuekai-china/vuepress-plugin-right-anchor#10]
点击返回顶部按钮后，锚点无法恢复到初始化状态

**Comment by xuek9900** [comment]
是的，正常时的确是这样，锚点只会记录你最后得操作，无法与官网的 back-to-top 通讯。
如果为此写一个侦听器来达到目的，会消耗很多性能。

**Comment by kk305cs** [comment]
感谢您的回复，我尝试过去掉debounce之后是可以达到目的的，就是有可能会消耗性能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xuekai-china"<notifications@github.com&gt;; 
发送时间: 2021年1月23日(星期六) 下午4:10
收件人: "xuekai-china/vuepress-plugin-right-anchor"<vuepress-plugin-right-anchor@noreply.github.com&gt;; 
抄送: "Katherine蓝羽"<693889176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuekai-china/vuepress-plugin-right-anchor] 与@vuepress/plugin-back-to-top一起使用时的问题 (#10)





 
是的，正常时的确是这样，锚点只会记录你最后得操作，无法与官网的 back-to-top 通讯。
 如果为此写一个侦听器来达到目的，会消耗很多性能。

**Comment by xuek9900** [comment]
你好像提醒了我，这里好像不应该用防抖，应该用节流，我试试。因为工作很久没回复你，不好意思。

**Comment by xuek9900** [comment]
fixed: in 0.4.8.
