### ISSUE TITLE
右侧导航栏内容可以显示，但无法显示功能按钮

### ISSUE THREAD

**Issue by IanXuCode** [xuekai-china/vuepress-plugin-right-anchor#13]
Hi, 感谢你的插件，目前右侧导航栏内容可以正确显示，但与示例相比，发现缺少了功能按钮，无法进行开启或关闭。
<img width="899" alt="WX20210517-193646@2x" src="https://user-images.githubusercontent.com/72936300/118483082-3171c500-b748-11eb-8016-19d1f97303b7.png">
<img width="909" alt="WX20210517-194411@2x" src="https://user-images.githubusercontent.com/72936300/118483167-4b130c80-b748-11eb-95c4-27a9172a458b.png">

**Comment by xuek9900** [comment]
我猜测，你的配置项  expand.trigger 应该是使用了 'hover'，改成 'click' 按钮就会出现，至于 'hover' 应该被我在某一版本改出了 bug。

**Comment by xuek9900** [comment]
如果不是因为 expand.trigger ，你可以把你的配置参数或者最小项目环境发出来让我帮你看看。

**Comment by xuek9900** [comment]
hover 模式确实存在设计缺陷，由于很久没有维护没有发现这个问题。我稍后会修复这个问题发布新的版本。

**Comment by xuek9900** [comment]
0.5.0 已经发布，按钮在俩种模式下都显示。

**Comment by IanXuCode** [comment]
已解决，非常感谢~
