### ISSUE TITLE
vuepress@next

### ISSUE THREAD

**Issue by ljcremer** [xuekai-china/vuepress-plugin-right-anchor#14]
Will this work with vuepress@next?

**Comment by xuekai-china** [comment]
> Will this work with vuepress@next?

Sorry, I don't know. I haven't tried and didn't with concern vuepress@next.

**Comment by xuek9900** [comment]
Sorry, I don't know. I haven't tried and didn't concern vuepress@next.

**Comment by xuek9900** [comment]
Once again, someone mentioned this problem. I plan to be compatible with the new version.

**Comment by xuek9900** [comment]
The work has been completed, see #17.
