### ISSUE TITLE
Add indents to headers above level 3

### ISSUE THREAD

**Issue by LeoHsiao1** [xuekai-china/vuepress-plugin-right-anchor#15]
Thank you for your plugin, it's very convenient.
I don't know Vue, but I'm hoping for a little improvement.
The current code only adds the `sub` class to level 3 header, with `padding-left: 30px;`.

https://github.com/xuekai-china/vuepress-plugin-right-anchor/blob/4dbe9a2a0e8665d5401c62a71ff174621a50eb03/RightAnchor.vue#L30

Can you add more indents to h4 and h5 headers?

**Comment by xuek9900** [comment]
ok，I will finish it.

**Comment by xuek9900** [comment]
Added，0.5.1 published!

**Comment by xuek9900** [comment]
At the same time, you may need to configure [here](https://vuepress.vuejs.org/zh/config/#markdown-extractheaders)(markdown.extractHeaders) if you want to display `h4` and `h5`...

```js
module.exports = {
  markdown: {
    extractHeaders: [ 'h2', 'h3', 'h4' ]
  }
}
```

**Comment by LeoHsiao1** [comment]
Thank you.

**Comment by xuek9900** [comment]
I just read your notes and they're great.
At the same time, I found a style error in `h2` hover, which I have fixed.
Your `h1` feature is very good, I also added it.

**Comment by LeoHsiao1** [comment]
Thanks.
I upgraded the plugin to version 0.5.2 .
