### ISSUE TITLE
Are there any plans to support VuePress v2?

### ISSUE THREAD

**Issue by jmaneyrol69** [xuekai-china/vuepress-plugin-right-anchor#17]
Hi,

VuePress v2, a.k.a vuepress@next, should be in stable state soon (see https://github.com/vuepress/vuepress-next/discussions/68 ) and my company is considering migrating to it. As we currently use this plugin, I would like to know whether there are any plans to port it to to vuepress@next?

Thank you.
Best regards

**Comment by xuek9900** [comment]
I'm glad this plugin can help you. I happen to have free time recently. I will upgrade the plugin in the next two days for vuepress@next , wait for my good news!

**Comment by xuek9900** [comment]
The work has been completed.
  - 2.x.x -> Vuepress 2.x -> master branch -> npm tag next
  - 0.x.x -> Vuepress 1.x -> legacy branch -> npm tag latest

**Comment by xuek9900** [comment]
Vuepress@next (vuepress V2) after npm tag is migrated to the latest version, I will perform the same operation.

**Comment by jmaneyrol69** [comment]
I've just tested it and it looks great!

Just one thing: in mobile size (width < 704px), the right anchor disappears. Thus, if `sidebarDepth` is set to 0 for the main sidebar plugin, there is no way to navigate within the page toc. This forces to set the value to 1 or greater, which is redundant when using the plugin.

Would it be possible to implement some mechanism that would force/switch `sidebarDepth` to 1 (or any value greater than 0) if width is lower than 704px ?

**Comment by xuek9900** [comment]
OK, let me think about this problem.

**Comment by xuek9900** [comment]
I tried. I can't help you. 

You can try this.

https://github.com/xuekai-china/vuepress-plugin-right-anchor/blob/84e9fea9e87e1be944a8e31f432a256d83983fd8/example/docs/.vuepress/config.js#L26
https://github.com/xuekai-china/vuepress-plugin-right-anchor/blob/84e9fea9e87e1be944a8e31f432a256d83983fd8/example/docs/.vuepress/styles/index.scss#L10-L12
