### ISSUE TITLE
Build failed after upgrading to 0.5.4

### ISSUE THREAD

**Issue by tchiotludo** [xuekai-china/vuepress-plugin-right-anchor#19]
My `package.json` :  
```
// before: 
    "vuepress-plugin-right-anchor": "^0.4.9",
// after: 
    "vuepress-plugin-right-anchor": "^0.5.4",
```

will emit this error : 

```
wait Rendering static HTML...
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'isIgnore' of undefined"

found in

---> <RightAnchor>
       <Root>
error Error rendering /404.html: false
undefined
TypeError: Cannot read property 'isIgnore' of undefined
    at VueComponent.filterDataByLevel (node_modules/vuepress-plugin-right-anchor/RightAnchor.vue:103:14)
```

**Comment by xuek9900** [comment]
I can't reproduce your problem. Can you show your configuration items to help me analyze this problem？

**Comment by tchiotludo** [comment]
I'll try to give you a reproduction steps but I can't ... 
I just try on my machine and it's work well, but always failed on [github actions](https://github.com/kestra-io/kestra.io/commit/9e9ba9a33cd08f503ee2b2983959b521bd42f8a2/checks).
The source code is [here](https://github.com/kestra-io/kestra.io), just change the version in `package.json` and it will failed only on github actions. 

the compiled code and the exception seems to mean `this.rightAnchorOption` is undefined here but I can't find this reference code in ts code : 
```js
    filterDataByLevel() {
      this.listData = [];

      const { headers } = this.$page;
      const { isIgnore, showDepth } = this.rightAnchorOption;

      if (isIgnore || showDepth === 0 || !headers) return;

```

**Comment by xuek9900** [comment]
OK, I see. I'll help you

**Comment by xuek9900** [comment]
try 0.5.5

**Comment by tchiotludo** [comment]
It's works perfectly, thanks :+1:
