### ISSUE TITLE
vuepress2版本报错

### ISSUE THREAD

**Issue by mikuwife** [xuekai-china/vuepress-plugin-right-anchor#22]

**Comment by mikuwife** [comment]
![屏幕截图 2022-03-19 105052](https://user-images.githubusercontent.com/50703346/159104258-cf8287ba-ee4d-44aa-afcd-6f79cde1f907.png)
版本是
```
"vuepress-plugin-right-anchor": "^2.0.0-rc.3"
"vuepress": "^2.0.0-beta.36",
```

**Comment by xuek9900** [comment]
好的，我周末看下问题。

**Comment by mikuwife** [comment]
请问一下目前解决了吗

**Comment by xuek9900** [comment]
问题在我本地已经解决，大致是因为 vuepress2.x beta.24 迭代到 beta.36 插件实现策略做的不兼容升级。我会在近俩天测试后发布。

**Comment by xuek9900** [comment]
有一点需要提醒你，vuepress2.x 的迭代进度有点慢，目前作为学习可以，如果是生产环境还是推荐用 1.x 比较好，相对稳定。2.x 在进入 rc 间断前很有可能再出现不兼容方案，这对生态跟进是个问题，所以也是我看到你的 issue 未及时跟进的原因。

**Comment by mikuwife** [comment]
好的，非常感谢

**Comment by hyp530** [comment]
这个错误仍然存在。 感谢作者。

**Comment by xuek9900** [comment]
> 这个错误仍然存在。 感谢作者。

好的 我争取今晚发布一版可用的。

**Comment by xuek9900** [comment]
已发布 2.0.0-rc.4

**Comment by mikuwife** [comment]
ok
