### ISSUE TITLE
Need more features on this plugin.

### ISSUE THREAD

**Issue by wxsms** [xuekai-china/vuepress-plugin-right-anchor#5]
First of all, thank you for such great plugin.

I'd like to see these features to be implemented:

1. Enable/disable by page, such as a frontmatter of the markdown.
2. Do not show if no anchors in page at all. (I consider this as a bug in current version)
3. Allow people to disable the global added right anchor, and use `RightAnchor` component to make their own.
4. Allow custom class.

Sounds good?

**Comment by xuekai-china** [comment]
> First of all, thank you for such great plugin.
> 
> I'd like to see these features to be implemented:
> 
> 1. Enable/disable by page, such as a frontmatter of the markdown.
> 2. Do not show if no anchors in page at all. (I consider this as a bug in current version)
> 3. Allow people to disable the global added right anchor, and use `RightAnchor` component to make their own.
> 4. Allow custom class.
> 
> Sounds good?

Thank you for your opinion. My English is not very good. If I have something about your description that I don't understand, can I contact you by email?

**Comment by xuek9900** [comment]
> First of all, thank you for such great plugin.
> 
> I'd like to see these features to be implemented:
> 
> 1. Enable/disable by page, such as a frontmatter of the markdown.
> 2. Do not show if no anchors in page at all. (I consider this as a bug in current version)
> 3. Allow people to disable the global added right anchor, and use `RightAnchor` component to make their own.
> 4. Allow custom class.
> 
> Sounds good?

I support some features in published '0.3.2'.

  1.  supported
  2. fixed
  3. I don't have a good design inspiration about this proposal, or the function should not have been in the plug-in‘s work 
      scope and my original design scope. If you need such a function, you can design a better plug-in based on my code. so 
      sorry.
  4. supported

**Comment by wxsms** [comment]
你好，我收到了你的邮件，但我还是希望在这里交流。请你谅解。

感谢你的支持，关于第3点，我可能会再有空的时候研究一下解决方案，并给你提交一个PR。

另外，我在使用过程中还发现了另外一个问题，即如果网站上存在一些动态加载的元素，如 [https://github.com/ulivz/vuepress-plugin-flowchart](https://github.com/ulivz/vuepress-plugin-flowchart)，这个插件的高度计算会产生误差，因为它仅在 mounted 之后计算了一次。关于这一点，不知道你有没有好的解决方案？

**Comment by wxsms** [comment]
目前我的解决方案是，在mounted之后以及5秒后，各进行一次计算。以及在每次点击anchor跳转之前也进行一次计算。但是我觉得这样不是很好。

**Comment by xuek9900** [comment]
> 你好，我收到了你的邮件，但我还是希望在这里交流。请你谅解。
> 
> 感谢你的支持，关于第3点，我可能会再有空的时候研究一下解决方案，并给你提交一个PR。
> 
> 另外，我在使用过程中还发现了另外一个问题，即如果网站上存在一些动态加载的元素，如 https://github.com/ulivz/vuepress-plugin-flowchart，这个插件的高度计算会产生误差，因为它仅在 mounted 之后计算了一次。关于这一点，不知道你有没有好的解决方案？

没关系，事后我也觉得稍有打扰，方式不妥。

动态加载的元素我觉得可以用 watcher 侦听 $page.headers 重新计算，毕竟所有的 anchor 都来自 headers，我没有测试场景，代码提供给你帮我来测试一下，如果可以你可以发 PR。
```js
  watch: {
    "$page.regularPath": function () {
      this.filterDataByLevel();
    },
   "$page.headers": function () {
      this.filterDataByLevel();
    },
  },
```
深表感谢🙏！

**Comment by wxsms** [comment]
动态内容并不涉及 `headers` 的更改，因此这个方案不行。
