### ISSUE TITLE
Separate colour for the menu toggle and the text

### ISSUE THREAD

**Issue by hamishwillee** [xuekai-china/vuepress-plugin-right-anchor#8]
Hi,
The current color set assigns same colour for the menu toggle and for the text. That means you can't have a menu with white text without the toggle disappearing.

![image](https://user-images.githubusercontent.com/5368500/98192577-64ecbf00-1f6f-11eb-80d6-5aab9736245e.png)

**Comment by xuek9900** [comment]
You want to set different colors for button text and menu item text, don't you?

**Comment by xuek9900** [comment]
Add more custom style variables in '0.4.5'.

```stylus
$rightAnchorBgColor = #fff;
$rightAnchorTextColor = $textColor;
$rightAnchorFontSize = 14px;
// btn
$rightAnchorBtnTextColor = $rightAnchorTextColor;
$rightAnchorBtnBgColor = $rightAnchorBgColor;
// menu
$rightAnchorMenuTextColor = $rightAnchorTextColor;
```

**Comment by hamishwillee** [comment]
Thanks! I'll test this tomorrow.

**Comment by hamishwillee** [comment]
Works well. Thank you.
