### ISSUE TITLE
点击跳转时是否可以增加a标签，可以跳转到该锚点

### ISSUE THREAD

**Issue by kk305cs** [xuekai-china/vuepress-plugin-right-anchor#9]
比如：http://xxx.com#head1，这样链接可以收藏，下次进入可以直接滚动到该锚点下

**Comment by xuek9900** [comment]
你的提议我会试下，但我猜很大可能会于 vuepress 内部机制冲突。等我试过告诉你，或者你可以贡献自己的代码！

**Comment by kk305cs** [comment]
感谢您的回复，我现在还是初学阶段，可能无法贡献自己的力量，我会尝试修改增加a标签




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xuekai-china"<notifications@github.com&gt;; 
发送时间: 2021年1月23日(星期六) 下午4:04
收件人: "xuekai-china/vuepress-plugin-right-anchor"<vuepress-plugin-right-anchor@noreply.github.com&gt;; 
抄送: "Katherine蓝羽"<693889176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuekai-china/vuepress-plugin-right-anchor] 点击跳转时是否可以增加a标签，可以跳转到该锚点 (#9)





 
你的提议我会试下，但我猜很大可能会于 vuepress 内部机制冲突。等我试过告诉你，或者你可以贡献自己的代码！

**Comment by xuek9900** [comment]
> 感谢您的回复，我现在还是初学阶段，可能无法贡献自己的力量，我会尝试修改增加a标签

我简单试一下，a 标签与 [@vuepress/plugin-active-header-links](https://vuepress.vuejs.org/zh/plugin/official/plugin-active-header-links.html) 还是会冲突的。如果有时间我会看看官方有没有 Api 让我来做这样的事，或者去读一下 active-header-links 的代码实现，这个功能暂时没法帮到你，抱歉！

**Comment by kk305cs** [comment]
好的，&nbsp;没事。还是非常感谢您的帮助，现在基本功能可以实现~有插件真好~谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xuekai-china"<notifications@github.com&gt;; 
发送时间: 2021年1月26日(星期二) 下午5:32
收件人: "xuekai-china/vuepress-plugin-right-anchor"<vuepress-plugin-right-anchor@noreply.github.com&gt;; 
抄送: "Katherine蓝羽"<693889176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuekai-china/vuepress-plugin-right-anchor] 点击跳转时是否可以增加a标签，可以跳转到该锚点 (#9)





  
感谢您的回复，我现在还是初学阶段，可能无法贡献自己的力量，我会尝试修改增加a标签
  
我简单试一下，a 标签与 [@vuepress/plugin-active-header-links(https://vuepress.vuejs.org/zh/plugin/official/plugin-active-header-links.html) 还是会冲突的。

**Comment by yzhang-gh** [comment]
+1 在点击跳转的时候（才）修改地址 anchor。官方自带的 active-header-links 乍一看很好用，但是用一段时间就发现稍微一滑动就把地址修改了。。。

看起来是这一句
https://github.com/vuejs/vuepress/blob/38e98634af117f83b6a32c8ff42488d91b66f663/packages/%40vuepress/plugin-active-header-links/clientRootMixin.js#L53
